# Generated by Django 2.2.9 on 2021-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
