# Generated by Django 2.2.9 on 2021-07-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210708_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='uploads/avatar'),
        ),
    ]
