# Generated by Django 3.1.2 on 2022-04-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('C', 'COMPLETED')], default='PENDING', max_length=30),
        ),
    ]
